CREATE SEQUENCE SEQ_MEDICAL_INSTITUTION AS INTEGER NO CYCLE CACHE 5;
CREATE SEQUENCE SEQ_STAFF AS INTEGER NO CYCLE CACHE 5;
CREATE SEQUENCE SEQ_PATIENT AS INTEGER NO CYCLE CACHE 5;
CREATE SEQUENCE SEQ_CYCLE_OF_PATIENT AS INTEGER NO CYCLE CACHE 5;
CREATE SEQUENCE SEQ_MEDICAL_HISTORY AS INTEGER NO CYCLE CACHE 5;
CREATE SEQUENCE SEQ_APPLICATION_TIMETABLE AS INTEGER NO CYCLE CACHE 5;
CREATE SEQUENCE SEQ_SURVEY AS INTEGER NO CYCLE CACHE 5;