CREATE TRIGGER ins1 BEFORE INSERT ON Cycle_of_patient REFERENCING NEW AS n FOR EACH ROW  WHEN (n.Date_of_admission > n.Date_of_leaving) SIGNAL SQLSTATE '75000' SET MESSAGE_TEXT='Bad dates range';

CREATE TRIGGER cascade1 AFTER DELETE ON PATIENT REFERENCING OLD AS o FOR EACH ROW DELETE FROM Patient_service p WHERE p.id_Patient = o.id_Patient;
CREATE TRIGGER cascade2 AFTER DELETE ON PATIENT REFERENCING OLD AS o FOR EACH ROW DELETE FROM Cycle_of_patient p WHERE p.id_Patient = o.id_Patient;
CREATE TRIGGER cascade3 AFTER DELETE ON PATIENT REFERENCING OLD AS o FOR EACH ROW DELETE FROM Survey_of_patient p WHERE p.id_Patient = o.id_Patient;